spatial: True # Whether to use spatial representations as inputs to A/C
train: False
predictive_net:
    load: True
    path: example_nets_donut_long_theta/thcycRNN_5win_full-theta-s8 #example_nets_donut_long_prev_action/thRNN_5win_prevAct-PrevAct-s8
    folder: '/home/mila/a/aleksei.efremov/pRNN-RL/'
    pRNNtype: thRNN_5win #AutoencoderPred_LN
    cell: LayerNormRNNCell
    lr: 2e-3
    bias_lr: 0.2
    bptttrunc: 1e8
    weight_decay: 3e-3
    ntimescale: 2
    dropout: 0.15
    noisemean: 0
    noisestd: 0.05
    sparsity: 0.5
    seqdur: 512 # Only relevant if train is on
    mask: 0 # Mask top x portion of neurons
    mask_type: 'SI' # Properties based on which mask is applied: 'SI', 'EV', or 'Dec'
    mask_bottom: False # Whether to mask bottom x portion of neurons instead of top x