input_type: 'CANN+PO'
exp_name: CANN+PO
pRNN: False # Wether to use pRNN for spatial input and/or internal reward
PC: False # Wether to use fake place cells for spatial input and/or internal reward
CANN: True # Wether to use CANN for spatial input and/or internal reward
recurrence: 1 # Wether to use RNN for memory (1 = don't use, other number = number of recurrent steps)
spatial: True # Wether to include spatial input
with_obs: True # Wether to include visual input (in case of recurrency the one that would bypass RNN)
rgb: True
intrinsic: False
theta: False