exp_name: Goal
goal_conditioned: True # Whether to condition the policy on the goal
check_location: True # Whether to check goal achievement based on location (exact match) instead of internal representation
exclude_goals: False
x_min: 5 # Minimum x-coordinate of the area to exclude from goal sampling
x_max: 11 # Maximum x-coordinate of the area to exclude from goal sampling
y_min: 10 # Minimum y-coordinate of the area to exclude from goal sampling
y_max: 16 # Maximum y-coordinate of the area to exclude from goal sampling
steps: 8e6