input_type: 'PC'
exp_name: PC+Intrinsic
PC: True # Wether to use fake place cells for spatial input and/or internal reward
spatial: True # Wether to include spatial input
intrinsic: True
with_HD: True