input_type: 'theta_pRNN'
exp_name: theta+int
pRNN: True # Whether to use pRNN for spatial input and/or internal reward
spatial: True # Whether to include spatial input
intrinsic: True
theta: True
shared_weights: True